Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [6]:
a = np.array(range(12,24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [23]:
x1 = a.reshape((6,2))
print(x1)
x2 = a.reshape((2,6))
print(x2)
x3 = a.reshape((3,4))
print(x3)
x4 = a.reshape((4,3))
print(x4)
x5 = a.reshape((12,1))
print(x5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [28]:
x1 = a.reshape((6,-1))
print(x1)
x2 = a.reshape((2,-1))
print(x2)
x3 = a.reshape((3,-1))
print(x3)
x4 = a.reshape((-1,3))
print(x4)
x5 = a.reshape((-1,1))
print(x5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Технически нет, поскольку обращение через один индекс (как в обычном одномерном массиве) даст нам массив а не элемент.. 

In [29]:
x5[1]

array([13])

In [30]:
x5[1][0]

13

In [31]:
x4.size

12

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [34]:
b = np.random.normal(0, 1, 12).reshape((3,4))
b

array([[-1.03201857, -0.86696065, -0.93125051, -0.56642749],
       [-0.46765478, -1.38033166,  0.05555626,  0.26812021],
       [-1.17152442, -0.57309163, -1.41736211,  0.78481104]])

In [35]:
b.size

12

In [38]:
b.reshape(1,12)[0]

array([-1.03201857, -0.86696065, -0.93125051, -0.56642749, -0.46765478,
       -1.38033166,  0.05555626,  0.26812021, -1.17152442, -0.57309163,
       -1.41736211,  0.78481104])

In [39]:
b.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [50]:
a = np.linspace(20, 0, 10, endpoint=False, dtype=int)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [49]:
b = np.linspace(20, 0, 10, endpoint=False, dtype=int).reshape((1,10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

массив b двумерный (технически) в отличии от a

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [56]:
a = np.zeros((2,2))
b = np.ones((3,2))
c = np.vstack((a, b))
print(c)
print(c.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


Наверное так?

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [65]:
a = np.array(range(0,12))
A = np.matrix(a.reshape((4,3)))
A

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [64]:
At = A.transpose()
At

matrix([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [71]:
B = A * At
B

matrix([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]])

In [72]:
np.linalg.det(B)

0.0

Не получится вычислить обратную. Поскольку полчуился редкий случай сингулярной матрицы (детерминант = 0)

In [73]:
np.linalg.inv(B)

LinAlgError: Singular matrix

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [74]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [77]:
c = np.random.randint(0, 16, 16)
c

array([ 8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14, 13, 13, 14, 13,  2])

Видимо всё